// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: identity.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DIDService_Authenticate_FullMethodName     = "/proto.DIDService/Authenticate"
	DIDService_IssueCredential_FullMethodName  = "/proto.DIDService/IssueCredential"
	DIDService_VerifyCredential_FullMethodName = "/proto.DIDService/VerifyCredential"
)

// DIDServiceClient is the client API for DIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DIDServiceClient interface {
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	IssueCredential(ctx context.Context, in *VerifiableCredential, opts ...grpc.CallOption) (*AuthResponse, error)
	VerifyCredential(ctx context.Context, in *VerifiableCredential, opts ...grpc.CallOption) (*AuthResponse, error)
}

type dIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDIDServiceClient(cc grpc.ClientConnInterface) DIDServiceClient {
	return &dIDServiceClient{cc}
}

func (c *dIDServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, DIDService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) IssueCredential(ctx context.Context, in *VerifiableCredential, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, DIDService_IssueCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) VerifyCredential(ctx context.Context, in *VerifiableCredential, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, DIDService_VerifyCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DIDServiceServer is the server API for DIDService service.
// All implementations must embed UnimplementedDIDServiceServer
// for forward compatibility.
type DIDServiceServer interface {
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	IssueCredential(context.Context, *VerifiableCredential) (*AuthResponse, error)
	VerifyCredential(context.Context, *VerifiableCredential) (*AuthResponse, error)
	mustEmbedUnimplementedDIDServiceServer()
}

// UnimplementedDIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDIDServiceServer struct{}

func (UnimplementedDIDServiceServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedDIDServiceServer) IssueCredential(context.Context, *VerifiableCredential) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCredential not implemented")
}
func (UnimplementedDIDServiceServer) VerifyCredential(context.Context, *VerifiableCredential) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCredential not implemented")
}
func (UnimplementedDIDServiceServer) mustEmbedUnimplementedDIDServiceServer() {}
func (UnimplementedDIDServiceServer) testEmbeddedByValue()                    {}

// UnsafeDIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DIDServiceServer will
// result in compilation errors.
type UnsafeDIDServiceServer interface {
	mustEmbedUnimplementedDIDServiceServer()
}

func RegisterDIDServiceServer(s grpc.ServiceRegistrar, srv DIDServiceServer) {
	// If the following call pancis, it indicates UnimplementedDIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DIDService_ServiceDesc, srv)
}

func _DIDService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_IssueCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifiableCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).IssueCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_IssueCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).IssueCredential(ctx, req.(*VerifiableCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_VerifyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifiableCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).VerifyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_VerifyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).VerifyCredential(ctx, req.(*VerifiableCredential))
	}
	return interceptor(ctx, in, info, handler)
}

// DIDService_ServiceDesc is the grpc.ServiceDesc for DIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DIDService",
	HandlerType: (*DIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _DIDService_Authenticate_Handler,
		},
		{
			MethodName: "IssueCredential",
			Handler:    _DIDService_IssueCredential_Handler,
		},
		{
			MethodName: "VerifyCredential",
			Handler:    _DIDService_VerifyCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
